#!/usr/bin/env bash
#
# Mission Control — Interactive Setup Wizard
#
# Usage:
#   curl -sSL <url>/setup.sh | bash
#   or: ./setup.sh
#
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║       Mission Control Setup          ║"
echo "  ║   Personal AI Command Center         ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${NC}"

# --- Check prerequisites ---

check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}✗ $1 is required but not installed.${NC}"
        echo "  Install it from: $2"
        exit 1
    fi
    echo -e "${GREEN}✓${NC} $1 found"
}

echo -e "${BOLD}Checking prerequisites...${NC}"
check_command "docker" "https://docs.docker.com/get-docker/"
check_command "docker" "https://docs.docker.com/compose/install/"

# Check Docker Compose (v2 plugin or standalone)
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
elif docker-compose version &> /dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}✗ Docker Compose is required but not found.${NC}"
    echo "  Install: https://docs.docker.com/compose/install/"
    exit 1
fi
echo -e "${GREEN}✓${NC} Docker Compose found"

# Check if Docker daemon is running
if ! docker info &> /dev/null 2>&1; then
    echo -e "${RED}✗ Docker daemon is not running. Start Docker and try again.${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} Docker daemon running"
echo ""

# --- Generate .env ---

if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists.${NC}"
    read -p "  Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "  Keeping existing .env"
        SKIP_ENV=true
    fi
fi

if [ "${SKIP_ENV:-false}" = "false" ]; then
    echo -e "${BOLD}LLM Provider Configuration${NC}"
    echo ""
    echo "  1) Anthropic API Key (recommended)"
    echo "  2) Claude Code OAuth Token (Pro/Max subscription)"
    echo "  3) OpenRouter API Key"
    echo "  4) Ollama (local, no key needed)"
    echo "  5) Skip (configure later)"
    echo ""
    read -p "  Choose provider [1-5]: " provider_choice

    API_KEY=""
    OAUTH_TOKEN=""
    OPENROUTER_KEY=""
    OLLAMA_URL=""

    case "${provider_choice:-1}" in
        1)
            read -p "  Anthropic API Key: " API_KEY
            ;;
        2)
            read -p "  OAuth Token: " OAUTH_TOKEN
            ;;
        3)
            read -p "  OpenRouter API Key: " OPENROUTER_KEY
            ;;
        4)
            OLLAMA_URL="${OLLAMA_URL:-http://host.docker.internal:11434}"
            echo "  Using Ollama at: $OLLAMA_URL"
            ;;
        5)
            echo "  Skipping LLM config (set it in .env later)"
            ;;
    esac

    # Database credentials
    echo ""
    PG_USER="missionctl"
    PG_PASS="missionctl"
    PG_DB="missioncontrol"
    read -p "  Database password [missionctl]: " custom_pass
    PG_PASS="${custom_pass:-missionctl}"

    # Telegram bot (optional)
    echo ""
    read -p "  Telegram Bot Token (optional, press Enter to skip): " TG_TOKEN
    TG_USERS=""
    if [ -n "$TG_TOKEN" ]; then
        read -p "  Allowed Telegram user IDs (comma-separated, or Enter for all): " TG_USERS
    fi

    # Write .env
    cat > .env << ENVEOF
# Mission Control - Generated by setup.sh
# $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# --- LLM Authentication ---
ANTHROPIC_API_KEY=${API_KEY}
CLAUDE_CODE_OAUTH_TOKEN=${OAUTH_TOKEN}
OPENROUTER_API_KEY=${OPENROUTER_KEY}
OLLAMA_BASE_URL=${OLLAMA_URL}

# --- Database ---
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=${PG_DB}

# --- Telegram Bot ---
TELEGRAM_BOT_TOKEN=${TG_TOKEN}
TELEGRAM_ALLOWED_USERS=${TG_USERS}

# --- Ports ---
API_PORT=8000
DASHBOARD_PORT=3000
DB_PORT=5432
REDIS_PORT=6379

# --- Agent Defaults ---
DEFAULT_MODEL=claude-haiku-4-5
SMART_MODEL=claude-sonnet-4-6
MAX_AGENT_BUDGET_USD=0.50
ENVEOF

    echo -e "${GREEN}✓${NC} .env file created"
fi

# --- Start services ---

echo ""
echo -e "${BOLD}Starting Mission Control...${NC}"
$COMPOSE_CMD up -d --build

# Wait for backend health
echo ""
echo -n "  Waiting for backend"
for i in {1..30}; do
    if curl -sf http://localhost:${API_PORT:-8000}/api/health > /dev/null 2>&1; then
        echo ""
        echo -e "${GREEN}✓${NC} Backend is healthy"
        break
    fi
    echo -n "."
    sleep 2
done

# Check if dashboard is up
if curl -sf http://localhost:${DASHBOARD_PORT:-3000} > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Dashboard is running"
fi

echo ""
echo -e "${GREEN}${BOLD}Mission Control is ready!${NC}"
echo ""
echo -e "  Dashboard:  ${CYAN}http://localhost:${DASHBOARD_PORT:-3000}${NC}"
echo -e "  API:        ${CYAN}http://localhost:${API_PORT:-8000}/api/health${NC}"
echo -e "  API Docs:   ${CYAN}http://localhost:${API_PORT:-8000}/docs${NC}"
echo ""
echo -e "  Useful commands:"
echo "    make status    — check service status"
echo "    make logs      — view logs"
echo "    make stop      — stop all services"
echo "    make test      — run tests"
echo ""
